apiVersion: v1
kind: Pod
metadata:
  name: lhci-pod
  labels:
    name: lhci-pod
spec:
  containers:
    - name: lhci-server
      image: docker.io/patrickhulce/lhci-server:0.5.0
      volumeMounts:
        - mountPath: '/data'
          name: lhci-data-volume
  volumes:
    - name: lhci-data-volume
      persistentVolumeClaim:
        claimName: lhci-data-claim
