sudo: required
dist: xenial
language: node_js
branches:
  only:
    - master # Only build master and PRs
matrix:
  include:
    - node_js: '10'
    - node_js: '11'
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - google-chrome-stable --version
  - export CHROME_PATH="$(which google-chrome-stable)"
  - export POSTGRES_DB_URL="postgres://postgres@localhost/lighthouse_ci_test"
  - psql -c 'create database lighthouse_ci_test;' -U postgres
script:
  - yarn build
  - yarn test
  - yarn ci:dogfood
before_cache:
  # nyc, jest and other projects store files in here. They mess up the travis build cache.
  - rm -rf ./node_modules/.cache/
services:
  - postgresql
  - xvfb
addons:
  chrome: stable
